"""Scientific models: constants, orbital mechanics, stellar physics.

Nothing in this package imports from :mod:`astro_explorer.data`,
:mod:`astro_explorer.ui` or :mod:`astro_explorer.rendering`.  It is the layer
the golden architecture rule (roadmap section 6) protects.
"""

from .constants import (
    AU,
    AU_PER_PARSEC,
    B_WIEN,
    C_LIGHT,
    G,
    H_PLANCK,
    K_BOLTZMANN,
    PARSEC,
    PARSEC_PER_AU,
    SIGMA_SB,
    SOLAR_EFFECTIVE_TEMPERATURE,
)
from .ephemeris import (
    TimeController,
    TimeMode,
    kepler_third_law_residual,
    period_from_semimajor_axis,
    semimajor_axis_from_period,
)
from .kepler import (
    eccentric_from_true_anomaly,
    kepler_residual,
    mean_anomaly_from_eccentric,
    solve_kepler,
    true_anomaly_from_eccentric,
)
from .orientation import (
    node_vector,
    orbit_normal,
    orbital_state,
    perifocal_velocity,
    position_from_eccentric_anomaly,
    rotation_perifocal_to_inertial,
    rotation_x,
    rotation_z,
    specific_angular_momentum,
)
from .state_vectors import (
    MU_SUN_AU3_PER_DAY2,
    StateVector,
    areal_velocity,
    expected_specific_energy,
    gravitational_parameter,
    specific_orbital_energy,
    state_at_eccentric_anomaly,
    swept_area,
    swept_area_binned,
    vis_viva_speed,
)
from .orbital_elements import (
    OrbitalElements,
    PhaseKnowledge,
    orbital_radius,
    perifocal_position,
    position_at_eccentric_anomaly,
    position_at_mean_anomaly,
    rotation_perifocal_to_reference,
    true_anomaly_at_mean_anomaly,
)
from .radiation import (
    BlackbodyCurve,
    SpectrumModel,
    blackbody_curve,
    planck_spectral_radiance,
    stefan_boltzmann_flux,
    wien_peak_wavelength,
)
from .stellar import (
    DiagramKind,
    HabitableZone,
    absolute_magnitude_from_luminosity,
    equilibrium_temperature,
    habitable_zone_au,
    insolation_earth_units,
    luminosity_from_radius_and_teff,
)

__all__ = [
    "MU_SUN_AU3_PER_DAY2",
    "StateVector",
    "areal_velocity",
    "expected_specific_energy",
    "gravitational_parameter",
    "node_vector",
    "orbit_normal",
    "orbital_state",
    "perifocal_velocity",
    "position_from_eccentric_anomaly",
    "rotation_perifocal_to_inertial",
    "rotation_x",
    "rotation_z",
    "specific_angular_momentum",
    "specific_orbital_energy",
    "state_at_eccentric_anomaly",
    "swept_area",
    "swept_area_binned",
    "vis_viva_speed",
    "AU",
    "AU_PER_PARSEC",
    "B_WIEN",
    "C_LIGHT",
    "G",
    "H_PLANCK",
    "K_BOLTZMANN",
    "PARSEC",
    "PARSEC_PER_AU",
    "SIGMA_SB",
    "SOLAR_EFFECTIVE_TEMPERATURE",
    "BlackbodyCurve",
    "DiagramKind",
    "HabitableZone",
    "OrbitalElements",
    "PhaseKnowledge",
    "SpectrumModel",
    "TimeController",
    "TimeMode",
    "absolute_magnitude_from_luminosity",
    "blackbody_curve",
    "eccentric_from_true_anomaly",
    "equilibrium_temperature",
    "habitable_zone_au",
    "insolation_earth_units",
    "kepler_residual",
    "kepler_third_law_residual",
    "luminosity_from_radius_and_teff",
    "mean_anomaly_from_eccentric",
    "orbital_radius",
    "perifocal_position",
    "period_from_semimajor_axis",
    "planck_spectral_radiance",
    "position_at_eccentric_anomaly",
    "position_at_mean_anomaly",
    "rotation_perifocal_to_reference",
    "semimajor_axis_from_period",
    "solve_kepler",
    "stefan_boltzmann_flux",
    "true_anomaly_at_mean_anomaly",
    "true_anomaly_from_eccentric",
    "wien_peak_wavelength",
]
